# Generated by Django 4.2.17 on 2025-02-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksRest', '0002_alter_tasksmodel_assigned_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='upodated_at',
            new_name='updated_at',
        ),
    ]
