# Generated by Django 4.2.17 on 2025-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksRest', '0003_rename_upodated_at_tasksmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='status',
            field=models.CharField(choices=[('Nowy', 'Nowy'), ('W toku', 'W toku'), ('Rozwiązany', 'Rozwiązany')], default='Nowy', max_length=50),
        ),
    ]
